language: php

php:
  - 5.5

before_script:
  - composer self-update
  - composer update
  - composer install --dev --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit -c phpunit.xml
